export const events = [
  {
    id: "1",
    name: "Noche de Pitch para Startups",
    date: "2024-09-15",
    location: "Bogotá, Colombia",
    description: "Una noche de networking y presentación para startups.",
    images: [
      "https://images.pexels.com/photos/1181393/pexels-photo-1181393.jpeg?auto=compress&cs=tinysrgb&w=600",
      "https://images.pexels.com/photos/326152/pexels-photo-326152.jpeg?auto=compress&cs=tinysrgb&w=600",
      "https://images.pexels.com/photos/1181393/pexels-photo-1181393.jpeg?auto=compress&cs=tinysrgb&w=600",
      "https://images.pexels.com/photos/326152/pexels-photo-326152.jpeg?auto=compress&cs=tinysrgb&w=600",
    ],
    videos: ["/videos/service-demo.mp4"],
    rating: 5,
    time: ["7:00 PM", "9:00 PM"],
    stock: 10,
    price: 500,
    providerInfo: {
      name: "Empresa San Jorge",
      contact: "contact@sanjorge.com",
    },
    reviews: [
      { username: "Luis", comment: "Evento de alta calidad.", rating: 5 },
      { username: "Carlos", comment: "Buena experiencia, espero con ansias la próxima edición.", rating: 4 },
    ],
  },
  {
    id: "2",
    name: "Taller de Emprendimiento 101",
    date: "2024-10-05",
    location: "Medellín, Colombia",
    description: "Un taller para nuevos y futuros emprendedores.",
    images: [
      "https://images.pexels.com/photos/3803863/pexels-photo-3803863.jpeg?auto=compress&cs=tinysrgb&w=600",
      "https://images.pexels.com/photos/1181705/pexels-photo-1181705.jpeg?auto=compress&cs=tinysrgb&w=600",
      "https://images.pexels.com/photos/3803863/pexels-photo-3803863.jpeg?auto=compress&cs=tinysrgb&w=600",
      "https://images.pexels.com/photos/1181705/pexels-photo-1181705.jpeg?auto=compress&cs=tinysrgb&w=600",
    ],
    videos: ["/videos/service-demo.mp4"],
    rating: 4,
    time: ["10:30 AM", "1:00 PM"],
    stock: 20,
    price: 500,
    providerInfo: {
      name: "Innovación y Desarrollo S.A.",
      contact: "info@innovacionydesarrollo.com",
    },
    reviews: [
      { username: "Maria", comment: "Gran taller, muy útil para los emprendedores principiantes.", rating: 4 },
      { username: "Ana", comment: "Bien organizado, aunque podría ser más interactivo.", rating: 3 },
    ],
  },
  {
    id: "3",
    name: "Cumbre de Innovadores Tecnológicos",
    date: "2024-11-20",
    location: "Cali, Colombia",
    description: "Una cumbre para innovadores tecnológicos y emprendedores.",
    images: [
      "https://images.pexels.com/photos/3932341/pexels-photo-3932341.jpeg?auto=compress&cs=tinysrgb&w=600",
      "https://images.pexels.com/photos/1239230/pexels-photo-1239230.jpeg?auto=compress&cs=tinysrgb&w=600",
      "https://images.pexels.com/photos/3932341/pexels-photo-3932341.jpeg?auto=compress&cs=tinysrgb&w=600",
      "https://images.pexels.com/photos/1239230/pexels-photo-1239230.jpeg?auto=compress&cs=tinysrgb&w=600",
    ],
    videos: ["/videos/service-demo.mp4"],
    rating: 3,
    time: ["2:00 PM", "5:00 PM"],
    stock: 30,
    price: 500,
    providerInfo: {
      name: "Tech Innovators Group",
      contact: "contact@techinnovators.com",
    },
    reviews: [
      { username: "Jorge", comment: "Interesante, pero faltó profundidad en algunos temas.", rating: 3 },
      { username: "Lucia", comment: "Buena oportunidad de networking con otros profesionales.", rating: 4 },
    ],
  },
  {
    id: "4",
    name: "Feria de Tecnología 2024",
    date: "2024-12-10",
    location: "Barranquilla, Colombia",
    description: "Exposición de las últimas innovaciones tecnológicas.",
    images: [
      "https://images.pexels.com/photos/407041/pancakes-maple-syrup-sweet-407041.jpeg?auto=compress&cs=tinysrgb&w=600",
      "https://images.pexels.com/photos/2122294/pexels-photo-2122294.jpeg?auto=compress&cs=tinysrgb&w=600",
      "https://images.pexels.com/photos/407041/pancakes-maple-syrup-sweet-407041.jpeg?auto=compress&cs=tinysrgb&w=600",
      "https://images.pexels.com/photos/2122294/pexels-photo-2122294.jpeg?auto=compress&cs=tinysrgb&w=600",
    ],
    videos: ["/videos/tech-fair.mp4"],
    rating: 4,
    time: ["9:00 AM", "6:00 PM"],
    stock: 50,
    price: 600,
    providerInfo: {
      name: "Tech Expo Co.",
      contact: "info@techexpo.com",
    },
    reviews: [
      { username: "Ricardo", comment: "Muy completa, ideal para profesionales del sector.", rating: 5 },
      { username: "Sandra", comment: "Buena feria, aunque esperaba más exhibiciones interactivas.", rating: 4 },
    ],
  },
  {
    id: "5",
    name: "Conferencia de Marketing Digital",
    date: "2024-09-28",
    location: "Cartagena, Colombia",
    description: "Conferencia sobre estrategias y herramientas de marketing digital.",
    images: [
      "https://images.pexels.com/photos/2615328/pexels-photo-2615328.jpeg?auto=compress&cs=tinysrgb&w=600",
      "https://images.pexels.com/photos/209267/pexels-photo-209267.jpeg?auto=compress&cs=tinysrgb&w=600",
      "https://images.pexels.com/photos/2615328/pexels-photo-2615328.jpeg?auto=compress&cs=tinysrgb&w=600",
      "https://images.pexels.com/photos/209267/pexels-photo-209267.jpeg?auto=compress&cs=tinysrgb&w=600",
    ],
    videos: ["/videos/marketing-conference.mp4"],
    rating: 4,
    time: ["8:00 AM", "4:00 PM"],
    stock: 25,
    price: 450,
    providerInfo: {
      name: "Digital Marketing Co.",
      contact: "contact@digitalmarketingco.com",
    },
    reviews: [
      { username: "Paola", comment: "Muy informativa, con excelentes ponentes.", rating: 5 },
      { username: "Esteban", comment: "Buena conferencia, pero el tiempo fue limitado.", rating: 4 },
    ],
  },
  {
    id: "6",
    name: "Encuentro de Emprendedores Locales",
    date: "2024-10-20",
    location: "Pereira, Colombia",
    description: "Encuentro para fomentar el emprendimiento local y regional.",
    images: [
      "https://images.pexels.com/photos/3810829/pexels-photo-3810829.jpeg?auto=compress&cs=tinysrgb&w=600",
      "https://images.pexels.com/photos/845451/pexels-photo-845451.jpeg?auto=compress&cs=tinysrgb&w=600",
      "https://images.pexels.com/photos/3810829/pexels-photo-3810829.jpeg?auto=compress&cs=tinysrgb&w=600",
      "https://images.pexels.com/photos/845451/pexels-photo-845451.jpeg?auto=compress&cs=tinysrgb&w=600",
    ],
    videos: ["/videos/entrepreneurs-meeting.mp4"],
    rating: 4,
    time: ["11:00 AM", "3:00 PM"],
    stock: 15,
    price: 300,
    providerInfo: {
      name: "Emprende Local",
      contact: "contact@emprendelocal.com",
    },
    reviews: [
      { username: "Fernando", comment: "Gran oportunidad para hacer contactos y aprender.", rating: 4 },
      { username: "Catalina", comment: "El evento estuvo bien, aunque el espacio era limitado.", rating: 3 },
    ],
  },
  {
    id: "7",
    name: "Summit de Inteligencia Artificial",
    date: "2024-11-15",
    location: "Bogotá, Colombia",
    description: "Un evento centrado en las últimas tendencias y desarrollos en inteligencia artificial.",
    images: [
      "https://images.pexels.com/photos/3825505/pexels-photo-3825505.jpeg?auto=compress&cs=tinysrgb&w=600",
      "https://images.pexels.com/photos/1054397/pexels-photo-1054397.jpeg?auto=compress&cs=tinysrgb&w=600",
      "https://images.pexels.com/photos/3825505/pexels-photo-3825505.jpeg?auto=compress&cs=tinysrgb&w=600",
      "https://images.pexels.com/photos/1054397/pexels-photo-1054397.jpeg?auto=compress&cs=tinysrgb&w=600",
    ],
    videos: ["/videos/ai-summit.mp4"],
    rating: 5,
    time: ["9:00 AM", "5:00 PM"],
    stock: 40,
    price: 700,
    providerInfo: {
      name: "AI Innovators",
      contact: "contact@aiinnovators.com",
    },
    reviews: [
      { username: "David", comment: "Excelente evento, muy relevante para el campo de la IA.", rating: 5 },
      { username: "Sara", comment: "Mucho contenido útil, aunque algunas charlas fueron muy técnicas.", rating: 4 },
    ],
  },
  {
    id: "8",
    name: "Workshop de Desarrollo Web",
    date: "2024-12-01",
    location: "Medellín, Colombia",
    description: "Un workshop intensivo sobre desarrollo web y nuevas tecnologías.",
    images: [
      "https://images.pexels.com/photos/4386368/pexels-photo-4386368.jpeg?auto=compress&cs=tinysrgb&w=600",
      "https://images.pexels.com/photos/518244/pexels-photo-518244.jpeg?auto=compress&cs=tinysrgb&w=600",
      "https://images.pexels.com/photos/4386368/pexels-photo-4386368.jpeg?auto=compress&cs=tinysrgb&w=600",
      "https://images.pexels.com/photos/518244/pexels-photo-518244.jpeg?auto=compress&cs=tinysrgb&w=600",
    ],
    videos: ["/videos/web-workshop.mp4"],
    rating: 4,
    time: ["10:00 AM", "4:00 PM"],
    stock: 25,
    price: 400,
    providerInfo: {
      name: "Web Dev Academy",
      contact: "info@webdevacademy.com",
    },
    reviews: [
      { username: "Natalia", comment: "Excelente workshop, muy práctico y bien dirigido.", rating: 4 },
      { username: "Felipe", comment: "Muy buen contenido, pero el ritmo fue un poco rápido.", rating: 4 },
    ],
  },
];
